version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.1
    steps:
      - checkout
      - setup_remote_docker
      - run: cp go.sum go.sum.orig
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum.orig" }}
      - run: |
          go get
          make bootstrap
          make all
      - run: |
          make test
      - store_test_results:
          path: bin/test/
      - store_artifacts: # upload test summary for display in Artifacts
          path: bin/test/
          destination: raw-test-output
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum.orig" }}
          paths:
            - "/go/pkg/mod"

  test_update_modules:
    docker:
      - image: circleci/golang:1.12.1
    steps:
      - checkout
      - run: |
          make update-modules

workflows:
  version: 2
  build_test_store_artifacts:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "30 3 * * *" # format: <minute> <hour> <day-month> <month> <day-week> -- so every day at 03:30 
          filters:
            branches:
              only: master
    jobs:     
      - test_update_modules
      - build:
          requires: 
            - test_update_modules

